import { useEffect, useState } from "react";
import { Check, Edit3, Plus, Search, Trash2, X } from "lucide-react";
import { apiError, money } from "../utils/formatters";

const empty = (fields) => Object.fromEntries(fields.map((field) => [field.name, field.type === "number" ? "" : ""]));

function ManagementPage({ title, description, service, fields, columns, moneyColumns = [] }) {
    const [rows, setRows] = useState([]); const [form, setForm] = useState(empty(fields));
    const [editing, setEditing] = useState(undefined); const [query, setQuery] = useState("");
    const [busy, setBusy] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
    const load = async () => { setBusy(true); try { setRows(await service.list()); setError(""); } catch (err) { setError(apiError(err, `Unable to load ${title.toLowerCase()}.`)); } finally { setBusy(false); } };
    useEffect(() => { load(); }, [title]);
    const open = (row = null) => { setEditing(row?.id || null); setForm(row ? Object.fromEntries(fields.map((field) => [field.name, row[field.name] ?? ""])) : empty(fields)); setError(""); };
    const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { await (editing ? service.update(editing, form) : service.create(form)); setNotice(editing ? "Updated successfully." : "Created successfully."); setEditing(undefined); await load(); } catch (err) { setError(apiError(err, `Unable to save ${title.toLowerCase()}.`)); } finally { setSaving(false); } };
    const remove = async (row) => { if (!window.confirm(`Delete ${row.name || "this record"}?`)) return; try { await service.remove(row.id); setNotice("Deleted successfully."); await load(); } catch (err) { setError(apiError(err, "Unable to delete this record.")); } };
    const visible = rows.filter((row) => columns.some((column) => String(row[column.key] ?? "").toLowerCase().includes(query.toLowerCase())));
    const renderInput = (field) => field.type === "select" ? <select required={field.required !== false} value={form[field.name]} onChange={(e) => setForm({ ...form, [field.name]: Number(e.target.value) })}><option value="">Select {field.label.toLowerCase()}</option>{field.options.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select> : field.type === "textarea" ? <textarea required={field.required !== false} value={form[field.name]} onChange={(e) => setForm({ ...form, [field.name]: e.target.value })} /> : <input required={field.required !== false} type={field.type || "text"} min={field.min} step={field.step} value={form[field.name]} onChange={(e) => setForm({ ...form, [field.name]: field.type === "number" ? Number(e.target.value) : e.target.value })} />;
    return <div className="page-container"><div className="page-header page-header-row"><div><p className="eyebrow">Workspace</p><h1>{title}</h1><p>{description}</p></div><button className="primary-button" onClick={() => open()}><Plus size={17} />Add {title.replace(/s$/, "")}</button></div>
        {notice && <div className="alert success"><Check size={17} />{notice}<button onClick={() => setNotice("")}><X size={16} /></button></div>}{error && <div className="alert error">{error}</div>}
        <div className="toolbar"><div className="search-box"><Search size={17} /><input placeholder={`Search ${title.toLowerCase()}...`} value={query} onChange={(e) => setQuery(e.target.value)} /></div><span className="result-count">{visible.length} records</span></div>
        <div className="table-wrap"><table><thead><tr>{columns.map((column) => <th key={column.key}>{column.label}</th>)}<th>Actions</th></tr></thead><tbody>{busy ? <tr><td colSpan={columns.length + 1} className="table-message">Loading...</td></tr> : visible.length === 0 ? <tr><td colSpan={columns.length + 1} className="table-message">No {title.toLowerCase()} found.</td></tr> : visible.map((row) => <tr key={row.id}>{columns.map((column) => <td key={column.key}>{moneyColumns.includes(column.key) ? money(row[column.key]) : column.key === "isActive" ? <span className={`status ${row[column.key] ? "active" : "inactive"}`}>{row[column.key] ? "Active" : "Inactive"}</span> : row[column.key] ?? "-"}</td>)}<td className="actions"><button className="icon-button" title="Edit" onClick={() => open(row)}><Edit3 size={16} /></button><button className="icon-button danger" title="Delete" onClick={() => remove(row)}><Trash2 size={16} /></button></td></tr>)}</tbody></table></div>
        {editing !== undefined && <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-header"><div><p className="eyebrow">{editing ? "Edit record" : "New record"}</p><h2>{editing ? `Edit ${title.replace(/s$/, "")}` : `Add ${title.replace(/s$/, "")}`}</h2></div><button type="button" className="icon-button" onClick={() => setEditing(undefined)}><X size={18} /></button></div><div className="form-grid">{fields.map((field) => <label key={field.name}>{field.label}{renderInput(field)}</label>)}</div><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setEditing(undefined)}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? "Saving..." : "Save"}</button></div></form></div>}
    </div>;
}
export default ManagementPage;