DELETE http://localhost:8080/api/inventory/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhdGhhcjg5QGV4YW1wbGUuY29tIiwiaWF0IjoxNzg1OTU2MzI3LCJleHAiOjE3ODYwNDI3Mjd9.BYwKX-eAz5R-AB4QPL99ZdVG4Eh0WZkXkbQwjuwuEdkHAOcWuU2ryDCwxX7y0HD_
###
PUT http://localhost:8080/api/inventory/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhdGhhcjg5QGV4YW1wbGUuY29tIiwiaWF0IjoxNzg1OTU2MzI3LCJleHAiOjE3ODYwNDI3Mjd9.BYwKX-eAz5R-AB4QPL99ZdVG4Eh0WZkXkbQwjuwuEdkHAOcWuU2ryDCwxX7y0HD_
Content-Type: application/json

{
  "productId": 2,
  "godownId": 2,
  "quantity": 200
}

###
GET http://localhost:8080/api/inventory/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhdGhhcjg5QGV4YW1wbGUuY29tIiwiaWF0IjoxNzg1OTU2MzI3LCJleHAiOjE3ODYwNDI3Mjd9.BYwKX-eAz5R-AB4QPL99ZdVG4Eh0WZkXkbQwjuwuEdkHAOcWuU2ryDCwxX7y0HD_
###
GET http://localhost:8080/api/inventory
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhdGhhcjg5QGV4YW1wbGUuY29tIiwiaWF0IjoxNzg2NzIwNzk4LCJleHAiOjE3ODY4MDcxOTh9.iwo9vwIxTOdADiTvZ5Cm4jupOzHG6KV0aq5pDBzbkTvnBapkobJQArYUvSp1FqRE

###
POST http://localhost:8080/api/inventory
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhdGhhcjg5QGV4YW1wbGUuY29tIiwiaWF0IjoxNzg2NzEyOTg3LCJleHAiOjE3ODY3OTkzODd9.3j-6h6D3_TDYubwyKWikXAhmZUnLjXk2ok_mru9ttPPFdkgymR0mOH1CG2YWsyMu
Content-Type: application/json

{
  "productId": 2,
  "godownId": 2,
  "quantity": 50
}

###
GET http://localhost:8080/api/products
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhdGhhcjg5QGV4YW1wbGUuY29tIiwiaWF0IjoxNzg2NzEyMzU5LCJleHAiOjE3ODY3OTg3NTl9.bIzYnkowS0ZnTGbSAN5EHTSvgyr716RWS__R0akCnn2UCwI9erS9YyrqQaAYYI5B

###
POST http://localhost:8080/api/inventory
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhdGhhcjg5QGV4YW1wbGUuY29tIiwiaWF0IjoxNzg2NzEyNzU3LCJleHAiOjE3ODY3OTkxNTd9.HvM6GZzLnT-TEG_L77AC6vCn32XQgspiKizCLV3d985OEYP-gjnOxoeYAHFGXSH7
Content-Type: application/json

{
  "productId": 2,
  "godownId": 2,
  "quantity": 100
}

