import { useEffect, useState } from "react";
import { Check, CreditCard } from "lucide-react";
import { purchaseService, saleService, paymentService } from "../services/entityService";
import { apiError, money } from "../utils/formatters";

function PaymentsPage({ supplier = false }) {
    const [records, setRecords] = useState([]); const [selected, setSelected] = useState(""); const [history, setHistory] = useState([]); const [form, setForm] = useState({ amount: "", paymentDate: new Date().toISOString().slice(0, 10), paymentMethod: "Cash", notes: "" }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
    useEffect(() => { (supplier ? purchaseService.list() : saleService.list()).then(setRecords).catch((err) => setError(apiError(err))).finally(() => setLoading(false)); }, [supplier]);
    const changeRecord = async (value) => { setSelected(value); setHistory([]); if (!value) return; try { setHistory(await (supplier ? paymentService.supplierHistory(value) : paymentService.customerHistory(value))); } catch (err) { setError(apiError(err)); } };
    const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const payload = { ...form, amount: Number(form.amount), [supplier ? "purchaseId" : "saleId"]: Number(selected) }; await (supplier ? paymentService.supplier(payload) : paymentService.customer(payload)); setMessage("Payment recorded successfully."); setForm({ ...form, amount: "", notes: "" }); await changeRecord(selected); } catch (err) { setError(apiError(err, "Unable to record payment.")); } finally { setSaving(false); } };
    return <div className="page-container"><div className="page-header"><p className="eyebrow">Accounts</p><h1>{supplier ? "Supplier Payments" : "Customer Payments"}</h1><p>Record payments against existing {supplier ? "purchases" : "sales"}.</p></div>{message && <div className="alert success"><Check size={17} />{message}</div>}{error && <div className="alert error">{error}</div>}<div className="payment-layout"><form className="panel" onSubmit={submit}><h2>Record payment</h2><label>{supplier ? "Purchase" : "Sale"}<select required value={selected} onChange={(e) => changeRecord(e.target.value)}><option value="">{loading ? "Loading..." : `Select ${supplier ? "purchase" : "sale"}`}</option>{records.map((record) => <option key={record.id} value={record.id}>#{record.id} · {supplier ? record.supplierName : record.customerName} · {money(record.totalAmount)}</option>)}</select></label><label>Amount<input required min="0.01" step="0.01" type="number" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></label><label>Payment date<input required type="date" value={form.paymentDate} onChange={(e) => setForm({ ...form, paymentDate: e.target.value })} /></label><label>Payment method<select value={form.paymentMethod} onChange={(e) => setForm({ ...form, paymentMethod: e.target.value })}><option>Cash</option><option>UPI</option><option>Bank transfer</option><option>Card</option><option>Cheque</option></select></label><label>Notes<textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label><button className="primary-button" disabled={!selected || saving}><CreditCard size={17} />{saving ? "Saving..." : "Record payment"}</button></form><section className="panel"><h2>Payment history</h2>{!selected ? <p className="muted">Select a record to view its payment history.</p> : history.length === 0 ? <p className="muted">No payments recorded yet.</p> : <div className="history-list">{history.map((payment) => <div className="history-row" key={payment.id}><div><strong>{money(payment.amount)}</strong><span>{payment.paymentDate} · {payment.paymentMethod}</span></div><span>{payment.notes || "-"}</span></div>)}</div>}</section></div></div>;
}
export const CustomerPaymentsPage = () => <PaymentsPage />;
export const SupplierPaymentsPage = () => <PaymentsPage supplier />;