import { useEffect, useState } from "react";
import { Eye, Plus, Trash2, X } from "lucide-react";
import { customerService, godownService, productService, purchaseService, saleService, supplierService } from "../services/entityService";
import { apiError, money } from "../utils/formatters";

function TransactionPage({ sale = false }) {
    const [rows, setRows] = useState([]); const [options, setOptions] = useState({ people: [], products: [], godowns: [] }); const [formOpen, setFormOpen] = useState(false); const [details, setDetails] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
    const [form, setForm] = useState({ partyId: "", godownId: "", date: new Date().toISOString().slice(0, 10), items: [{ productId: "", quantity: 1, price: "" }] });
    const service = sale ? saleService : purchaseService;
    const load = async () => { setLoading(true); try { setRows(await service.list()); setError(""); } catch (err) { setError(apiError(err, `Unable to load ${sale ? "sales" : "purchases"}.`)); } finally { setLoading(false); } };
    useEffect(() => { load(); Promise.all([sale ? customerService.list() : supplierService.list(), productService.list(), godownService.list()]).then(([people, products, godowns]) => setOptions({ people, products, godowns })).catch((err) => setError(apiError(err, "Unable to load form options."))); }, [sale]);
    const updateItem = (index, changes) => setForm({ ...form, items: form.items.map((item, itemIndex) => itemIndex === index ? { ...item, ...changes } : item) });
    const selectProduct = (index, value) => { const product = options.products.find((item) => String(item.id) === value); updateItem(index, { productId: value, price: product ? (sale ? product.sellingPrice : product.purchasePrice) : "" }); };
    const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); const payload = { [sale ? "customerId" : "supplierId"]: Number(form.partyId), godownId: Number(form.godownId), [sale ? "saleDate" : "purchaseDate"]: form.date, items: form.items.map((item) => ({ productId: Number(item.productId), quantity: Number(item.quantity), [sale ? "sellingPrice" : "purchasePrice"]: Number(item.price) })) }; try { await service.create(payload); setNotice(`${sale ? "Sale" : "Purchase"} created successfully.`); setFormOpen(false); await load(); } catch (err) { setError(apiError(err, `Unable to create ${sale ? "sale" : "purchase"}.`)); } finally { setSaving(false); } };
    const remove = async (row) => { if (!window.confirm(`Delete ${sale ? "sale" : "purchase"} #${row.id}?`)) return; try { await service.remove(row.id); setNotice("Deleted successfully."); await load(); } catch (err) { setError(apiError(err, "Unable to delete this transaction.")); } };
    const openNew = () => { setForm({ partyId: "", godownId: "", date: new Date().toISOString().slice(0, 10), items: [{ productId: "", quantity: 1, price: "" }] }); setFormOpen(true); setError(""); };
    return <div className="page-container"><div className="page-header page-header-row"><div><p className="eyebrow">Transactions</p><h1>{sale ? "Sales" : "Purchases"}</h1><p>{sale ? "Create customer sales and reduce stock through the backend." : "Create supplier purchases and increase stock through the backend."}</p></div><button className="primary-button" onClick={openNew}><Plus size={17} />New {sale ? "sale" : "purchase"}</button></div>{notice && <div className="alert success">{notice}<button onClick={() => setNotice("")}><X size={16} /></button></div>}{error && <div className="alert error">{error}</div>}<div className="table-wrap"><table><thead><tr><th>ID</th><th>{sale ? "Customer" : "Supplier"}</th><th>Godown</th><th>Date</th><th>Total</th><th>Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan="6" className="table-message">Loading...</td></tr> : rows.length === 0 ? <tr><td colSpan="6" className="table-message">No {sale ? "sales" : "purchases"} found.</td></tr> : rows.map((row) => <tr key={row.id}><td>#{row.id}</td><td>{sale ? row.customerName : row.supplierName}</td><td>{row.godownName}</td><td>{sale ? row.saleDate : row.purchaseDate}</td><td>{money(row.totalAmount)}</td><td className="actions"><button className="icon-button" title="View details" onClick={() => setDetails(row)}><Eye size={16} /></button><button className="icon-button danger" title="Delete" onClick={() => remove(row)}><Trash2 size={16} /></button></td></tr>)}</tbody></table></div>
        {formOpen && <div className="modal-backdrop"><form className="modal transaction-modal" onSubmit={submit}><div className="modal-header"><div><p className="eyebrow">New transaction</p><h2>Create {sale ? "sale" : "purchase"}</h2></div><button type="button" className="icon-button" onClick={() => setFormOpen(false)}><X size={18} /></button></div><div className="form-grid two"><label>{sale ? "Customer" : "Supplier"}<select required value={form.partyId} onChange={(e) => setForm({ ...form, partyId: e.target.value })}><option value="">Select {sale ? "customer" : "supplier"}</option>{options.people.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></label><label>Godown<select required value={form.godownId} onChange={(e) => setForm({ ...form, godownId: e.target.value })}><option value="">Select godown</option>{options.godowns.map((godown) => <option key={godown.id} value={godown.id}>{godown.name} · {godown.location}</option>)}</select></label><label>Date<input required type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /></label></div><div className="items-header"><h3>Items</h3><button type="button" className="secondary-button" onClick={() => setForm({ ...form, items: [...form.items, { productId: "", quantity: 1, price: "" }] })}><Plus size={15} />Add item</button></div>{form.items.map((item, index) => <div className="item-row" key={index}><select required value={item.productId} onChange={(e) => selectProduct(index, e.target.value)}><option value="">Select product</option>{options.products.map((product) => <option key={product.id} value={product.id}>{product.name} · {product.sku}</option>)}</select><input required min="1" type="number" value={item.quantity} onChange={(e) => updateItem(index, { quantity: e.target.value })} /><input required min="0.01" step="0.01" type="number" placeholder={sale ? "Selling price" : "Purchase price"} value={item.price} onChange={(e) => updateItem(index, { price: e.target.value })} /><button type="button" className="icon-button danger" disabled={form.items.length === 1} onClick={() => setForm({ ...form, items: form.items.filter((_, itemIndex) => itemIndex !== index) })}><Trash2 size={16} /></button></div>)}<div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setFormOpen(false)}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? "Saving..." : `Create ${sale ? "sale" : "purchase"}`}</button></div></form></div>}
        {details && <div className="modal-backdrop"><section className="modal"><div className="modal-header"><div><p className="eyebrow">Transaction details</p><h2>{sale ? "Sale" : "Purchase"} #{details.id}</h2></div><button className="icon-button" onClick={() => setDetails(null)}><X size={18} /></button></div><div className="detail-grid"><span>{sale ? "Customer" : "Supplier"}<strong>{sale ? details.customerName : details.supplierName}</strong></span><span>Godown<strong>{details.godownName}</strong></span><span>Date<strong>{sale ? details.saleDate : details.purchaseDate}</strong></span><span>Total<strong>{money(details.totalAmount)}</strong></span></div><div className="table-wrap"><table><thead><tr><th>Product</th><th>Quantity</th><th>Price</th><th>Subtotal</th></tr></thead><tbody>{details.items?.map((item) => <tr key={item.id}><td>{item.productName}</td><td>{item.quantity}</td><td>{money(sale ? item.sellingPrice : item.purchasePrice)}</td><td>{money(item.subtotal)}</td></tr>)}</tbody></table></div></section></div>}
    </div>;
}
export const PurchasesPage = () => <TransactionPage />;
export const SalesPage = () => <TransactionPage sale />;